[package]
name = "provola"
version = "0.1.7"
authors = ["Alessandro Pezzato <alessandro@pezzato.net>"]
edition = "2021"
description = "A tool for quick development/test cycle in any language"
homepage = "https://github.com/alepez/provola"
repository = "https://github.com/alepez/provola"
readme = "README.md"
license = "Apache-2.0"

[dependencies]
clap = { version = "3.0.0-beta.5", features = [ "derive" ] }
clap_generate = "3.0.0-beta.5"
env_logger = "0.9"
log = "0.4"

[dependencies.provola-core]
version = "0.1.7"
path = "provola-core"

[dependencies.provola-testrunners]
version = "0.1.7"
path = "provola-testrunners"

[dependencies.provola-reporters]
version = "0.1.7"
path = "provola-reporters"

[dependencies.provola-gtk]
version = "0.1.7"
path = "provola-gtk"
optional = true

[features]
default = []
gtk = [ "provola-gtk" ]

[workspace]

members = [
  "provola-core",
  "provola-reporters",
  "provola-googletest",
  "provola-catch2",
  "provola-testrunners",
  "provola-terminalreporter",
  "provola-gtk",
]
