[package]
name = "provola-core"
version = "0.1.0"
authors = ["Alessandro Pezzato <alessandro@pezzato.net>"]
edition = "2018"

[dependencies]
log = "*"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
