[package]
name = "provola-googletest"
version = "0.1.0"
edition = "2018"

[dependencies]
chrono = "0.4"
provola-core = { version = "0.1.4", path = "../provola-core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
