[package]
name = "provola-cli"
version = "0.1.0"
authors = ["Alessandro Pezzato <alessandro@pezzato.net>"]
edition = "2018"

[dependencies]
env_logger = "0.9"
log = "0.4"
provola-core = { path = "../provola-core" }
structopt = { version = "0.3" }
