#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "${SCRIPT_DIR}"
cd ..

git submodule update --init --recursive
mkdir build
cd build
cmake ..
cmake --build .
./example --gtest_output=json
mv test_detail.json ../test_report.json
