#!/usr/bin/env bash

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "${THIS_DIR}/_common"

open_editor() {
  local dir=$1
  (
    cd $dir
    ${EDITOR} Cargo.toml
  )
}

main() {
  local version=$1
  for_all_crates open_editor
}

main $1
