#!/usr/bin/env bash

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "${THIS_DIR}/_common"

cargo_path() {
  local dir=$1
  (
    cd $dir
    echo $(pwd)/Cargo.toml
  )
}

main() {
  local version=$1
  local cargo_paths=$( for_all_crates cargo_path )
  ${EDITOR} $cargo_paths
}

main $1
