name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: default
        override: true

    - uses: Swatinem/rust-cache@v1.3.0

    - run: |
        cargo install cargo-deny --locked
        cargo check
        cargo test
        cargo clippy
